package com.homerun.common.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.UUID;

/**
 * Persisted expectation record shared between pitcher (writer) and batter (reader).
 *
 * <p>Lookup key: {@code (scenarioId, targetService, operationName)} — enforced as a
 * unique compound index so a scenario may hold exactly one expectation per service
 * operation.
 *
 * <p>{@code serializedRequest} and {@code serializedResponse} are stored as raw JSON
 * strings so the document schema stays schema-free across any downstream service type.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "mock_expectations")
@CompoundIndex(
        name   = "scenario_service_op_uidx",
        def    = "{ 'scenarioId': 1, 'targetService': 1, 'operationName': 1 }",
        unique = true
)
public class MockExpectation {

    @Id
    private String id;

    /** UUID generated by the test before submitting expectations. */
    @Indexed
    private UUID scenarioId;

    /** Logical key for the downstream service, e.g. {@code "payments"}. */
    private String targetService;

    /**
     * Method/operation name on the client interface, e.g. {@code "charge"}.
     * Used together with {@code targetService} to disambiguate multiple
     * operations within the same service.
     */
    private String operationName;

    /**
     * JSON serialization of the request object the backend would send to the
     * downstream service. Stored for audit and optional strict-match verification;
     * not used for routing.
     */
    private String serializedRequest;

    /**
     * JSON serialization of the response the downstream service should return.
     * The batter deserializes this back into the concrete return type declared
     * by the mock client method.
     */
    private String serializedResponse;

    /** Controls how the mock behaves when invoked. Defaults to {@link MockBehaviorType#SUCCESS}. */
    @Builder.Default
    private MockBehaviorType behaviorType = MockBehaviorType.SUCCESS;

    // ── Error-scenario fields ─────────────────────────────────────────────────

    /**
     * Fully-qualified class name of the exception to throw.
     * Required when {@code behaviorType} is {@link MockBehaviorType#BUSINESS_ERROR}.
     */
    private String errorClassName;

    /** Human-readable message passed to the thrown exception. */
    private String errorMessage;

    /** HTTP status code for {@link MockBehaviorType#HTTP_ERROR} scenarios. */
    private Integer httpStatus;

    /** Milliseconds to sleep before throwing for {@link MockBehaviorType#TIMEOUT} scenarios. */
    private Long delayMillis;

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    /** Identity of the test or CI job that created this expectation. */
    private String createdBy;
    private Instant createdAt;

    /**
     * Hard expiry timestamp. The batter rejects invocations after this point.
     * Allows expectations to self-expire between test runs without explicit cleanup.
     */
    private Instant expiresAt;

    // ── Observability ─────────────────────────────────────────────────────────

    /** Incremented each time the batter serves this expectation. */
    @Builder.Default
    private int invocationCount = 0;

    private Instant lastInvokedAt;

    /** Free-text description for human-readable audit log entries. */
    private String description;

    /** Groups expectations that belong to the same test suite for bulk cleanup. */
    private String testSuiteName;
}
